id: IB38C4208
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T22:00:35.895991'
last_modified: '2022-05-30T22:00:35.896001'
parser: null
source_metadata:
  title: Karse Kongtrul Khyentse Özer
  language: en
  description: 'Texts by and about Karse Kongtrul Khyentse Özer (kar sras kong sprul
    mkhyen brtse''i ''od zer, 1904–c.1953) who was a reincarnation of Jamgön Kongtrul
    and son of the Fifteenth Karmapa:'
  volume:
    f8A98:
      title: Prayer to Karma Palden Khyentse
      base_file: f8A98.txt
      order: 1
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
